// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApXe6eGbVQZGn_tyq_dI3wIhJ_tM09Hvw',
    appId: '1:246928857627:web:3731d46e45b0828c0176be',
    messagingSenderId: '246928857627',
    projectId: 'fir-storge-de5cb',
    authDomain: 'fir-storge-de5cb.firebaseapp.com',
    databaseURL: 'https://fir-storge-de5cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-storge-de5cb.appspot.com',
    measurementId: 'G-YPJPKVCPV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuzn4d0grm4Blx-usQLMrsQU-IbFkZ33w',
    appId: '1:246928857627:android:3567d31b0cbb64470176be',
    messagingSenderId: '246928857627',
    projectId: 'fir-storge-de5cb',
    databaseURL: 'https://fir-storge-de5cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-storge-de5cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB25OaFFir5IWZDY505qMckCjuJhYFIlzA',
    appId: '1:246928857627:ios:bdc24f4751f8ad970176be',
    messagingSenderId: '246928857627',
    projectId: 'fir-storge-de5cb',
    databaseURL: 'https://fir-storge-de5cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-storge-de5cb.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB25OaFFir5IWZDY505qMckCjuJhYFIlzA',
    appId: '1:246928857627:ios:bdc24f4751f8ad970176be',
    messagingSenderId: '246928857627',
    projectId: 'fir-storge-de5cb',
    databaseURL: 'https://fir-storge-de5cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-storge-de5cb.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApXe6eGbVQZGn_tyq_dI3wIhJ_tM09Hvw',
    appId: '1:246928857627:web:c29fa25ba49cab180176be',
    messagingSenderId: '246928857627',
    projectId: 'fir-storge-de5cb',
    authDomain: 'fir-storge-de5cb.firebaseapp.com',
    databaseURL: 'https://fir-storge-de5cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-storge-de5cb.appspot.com',
    measurementId: 'G-0F4BFNX2B1',
  );
}
